### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by ivonigC** [activitree/s3up-meta#4]
If it may help some other users or maybe be added to the doc:

Package needs to add meteor sessions:

`meteor add session
`
import names are:

` { delete_files, upload_file, upload_files }
` 
 and not like the one in the example:
 
`  { deleteFiles, uploadFile, uploadFiles }
`

If you want an example implementation in react/ts without redux I can post it here with pleasure

**Comment by paulincai** [comment]
Please consider this a proprietary implementation and forking is advisable. Some things may change inside the package without proper updating of the Readme or other documentation. If you think this package is worth it please do fork it and publish a more generic version of it. We avoided doing that because we wanted to keep it published via Github and be able to take it private if necessary at some point.
